# Generated by Django 4.1 on 2022-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='member_id',
            field=models.CharField(max_length=20),
        ),
    ]
