# Generated by Django 4.0.6 on 2022-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('col1', models.AutoField(primary_key=True, serialize=False)),
                ('col2', models.CharField(max_length=20)),
                ('col3', models.DateField(auto_now=True)),
            ],
        ),
    ]
