# Generated by Django 4.0.4 on 2022-07-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_join_date',
        ),
    ]
