# Generated by Django 4.0.4 on 2022-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member2',
            fields=[
                ('test_col1', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('test_col2', models.CharField(max_length=20)),
                ('test_col3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
