# Generated by Django 4.1 on 2022-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(max_length=20, verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.CharField(max_length=20, verbose_name='상품가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_rate',
            field=models.CharField(max_length=20, verbose_name='할인율'),
        ),
    ]
