# Generated by Django 4.1 on 2022-08-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feed_code', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=20)),
                ('feed_title', models.CharField(max_length=50)),
                ('feed_content', models.TextField()),
                ('feed_pic', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('feed_date', models.DateTimeField(auto_now_add=True)),
                ('feed_like', models.IntegerField(default=0)),
                ('feed_hit', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
