# Generated by Django 4.1 on 2022-08-18 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('feed_reply_code', models.AutoField(primary_key=True, serialize=False)),
                ('feed_reply_content', models.TextField()),
                ('feed_date', models.DateTimeField(auto_now_add=True)),
                ('feed_code', models.ForeignKey(db_column='feed_code', on_delete=django.db.models.deletion.CASCADE, related_name='feed_code_reply', to='feed.feed')),
                ('member_id', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
