# Generated by Django 4.1 on 2022-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField(verbose_name='상품번호')),
                ('item_name', models.CharField(max_length=20, verbose_name='상품명')),
                ('item_price', models.PositiveIntegerField(verbose_name='상품가격')),
                ('item_rate', models.CharField(max_length=5, verbose_name='할인율')),
                ('item_link', models.URLField(verbose_name='링크')),
            ],
        ),
    ]
